repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: flake8
            args: ["--ignore=E203,E501,W503"]
  -   repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
        -  id: isort
           args: ["--profile", "black"]
  -   repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        -   id: black
